title: KDD25 Tutorial - Diffusion Models for Recommender Systems
description: From Content Distribution To Content Creation
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
github:
  repository_name: KDD25-DiffRec-Tutorial
  
# Site settings
lang: en
timezone: UTC

# Build settings
markdown: kramdown
highlighter: rouge 